---
extends: default

rules:
  line-length:
    max: 120
    level: warning

  document-start:
    present: true

  trailing-spaces:
    level: error

  new-line-at-end-of-file:
    level: error

  truthy:
    allowed-values: ['true', 'false']
    level: warning
